### PR TITLE
Feature/unsupervised training

### LINKED ISSUE #18: unsupervised pre-training

### PR DESCRIPTION
**Pull request by cregouby**
Hello, 
Unsupervised training is working now, and can be part of training scenario ( see test-hardhat-scenarios.R)
except for CUDA where I can't get `torch_bernoulli()` work on GPU (see https://github.com/mlverse/torch/issues/480)
Fix #18

### CODE REVIEW

**Comment by dfalbel** [comment]
Hey @cregouby ! This looks awesome!! It's almost there!
I have pushed some changes. 

I think the problem was that the decoder was returning only the combined steps output instead of the intermediate ones. 

We now get to a `print("Done")` but fails in serialization.
Let me know if this is helpful!

**Comment by cregouby** [comment]
Thanks a lot for this push ! I'll definitively continue with the model serialization.

**Review by dfalbel — APPROVED** [review]
Awesome @cregouby ! Merging now!

**Comment by cregouby** [comment]
Thanks a lot, @dfalbel  !

**Pull request merged**
