### PR TITLE
Feature/autoplot

### LINKED ISSUE #33: implement autoplot.tabnet_fit()
image

### PR DESCRIPTION
**Pull request by cregouby**
fix #33 
autoplot covers tabnet_fit, tabnet_pretrain and tabnet_explain S3 class

### CODE REVIEW

**Comment by dfalbel** [comment]
We might want to dynamically export the autoplot S3 method with something like:

https://github.com/mlverse/tabnet/blob/main/R/package.R#L2

**Comment by cregouby** [comment]
@dfalbel , I can't find a way to workaround the R CMD Check Warning on `autoplot`. Any help appreciated.

**Comment by dfalbel** [comment]
Thanks @cregouby ! I'll take a look at this next week!

**Comment by cregouby** [comment]
Thanks @dfalbel !

**Pull request merged**
